//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco_Amigo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_preguntas
    {
        public int pr_idpregunta { get; set; }
        public string pr_pregunta { get; set; }
        public string pr_estado { get; set; }
    
        public virtual ba_respuestausuario ba_respuestausuario { get; set; }
    }
}
