//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco_Amigo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ba_persona()
        {
            this.ba_usuarios = new HashSet<ba_usuarios>();
        }
    
        public int pe_idpersona { get; set; }
        public string pe_cedula { get; set; }
        public string pe_nombre { get; set; }
        public string pe_apellido { get; set; }
        public Nullable<System.DateTime> pe_fecha_nacimiento { get; set; }
        public string pe_direccion { get; set; }
        public string pe_sexo { get; set; }
        public string pe_correo { get; set; }
        public string pe_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ba_usuarios> ba_usuarios { get; set; }
    }
}
