//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco_Amigo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ba_roles()
        {
            this.ba_usuarios = new HashSet<ba_usuarios>();
        }
    
        public int ro_idrol { get; set; }
        public string ro_rol { get; set; }
        public string ro_estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ba_usuarios> ba_usuarios { get; set; }
    }
}
