//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco_Amigo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ba_usuarios()
        {
            this.ba_respuestausuario = new HashSet<ba_respuestausuario>();
        }
    
        public int us_idusuario { get; set; }
        public int us_idpersona { get; set; }
        public int us_idrol { get; set; }
        public string us_usuario { get; set; }
        public string us_clave { get; set; }
        public System.DateTime us_fecha_registro { get; set; }
        public Nullable<System.DateTime> us_fecha_modificacion { get; set; }
        public string us_estado { get; set; }
    
        public virtual ba_persona ba_persona { get; set; }
        public virtual ba_roles ba_roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ba_respuestausuario> ba_respuestausuario { get; set; }
    }
}
