//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;

namespace Banco_Amigo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_usuarios
    {
        public int us_idusuario { get; set; }
        public int us_idpersona { get; set; }
        public int us_idrol { get; set; }
        [DisplayName("Usuario")]
        public string us_usuario { get; set; }
        [DisplayName("Clave")]
        public string us_clave { get; set; }
        public System.DateTime us_fecha_registro { get; set; }
        public Nullable<System.DateTime> us_fecha_modificacion { get; set; }
        public string us_estado { get; set; }
    
        public virtual ba_persona ba_persona { get; set; }
        public virtual ba_roles ba_roles { get; set; }
    }
}
