//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco_Amigo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BancoAmigoEntities : DbContext
    {
        public BancoAmigoEntities()
            : base("name=BancoAmigoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ba_persona> ba_persona { get; set; }
        public virtual DbSet<ba_roles> ba_roles { get; set; }
        public virtual DbSet<ba_usuarios> ba_usuarios { get; set; }
        public virtual DbSet<ba_respuestausuario> ba_respuestausuario { get; set; }
        public virtual DbSet<ba_preguntas> ba_preguntas { get; set; }
    
        public virtual int sp_ValidaRegistroUsuario(string correo, string clave, ObjectParameter cod, ObjectParameter mensaje)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ValidaRegistroUsuario", correoParameter, claveParameter, cod, mensaje);
        }
    }
}
